Repository junesung1004/dallaem, pull requests merged in 2025-02, with the labels that each got.

#24 style: home layout width값 수정 및 헤더 컴포넌트 width값 수정
  public/images/save.png
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/_tests/Button.tsx
  src/app/api/todo.ts
  src/app/components/Header.tsx
  src/app/components/cardlist/Card.tsx
  src/app/components/cardlist/CardList.tsx
  src/app/hooks/query/useTodo.tsx
Labels: 스타일 관련 라벨

#25 Feature/tailwind config 속성 추가
  src/app/(auth)/signup/page.tsx
  src/app/(home)/@createmodal/createmodal/page.tsx
  src/app/(home)/layout.tsx
  src/app/components/cardlist/Card.tsx
  tailwind.config.ts
Labels: config 관련 라벨

#31 Feature/tailwind config
  src/app/components/cardlist/Card.tsx
  tailwind.config.ts
Labels: config 관련 라벨

#43 feat: 공통 컴포넌트 HeartRatings 추가
  src/app/(home)/mypage/page.tsx
  src/app/components/HeartRatings/Heart.tsx
  src/app/components/HeartRatings/HeartList.tsx
  src/app/components/HeartRatings/HeartRatings.tsx
  src/app/components/HeartRatings/HeartRatingsInteractive.tsx
Labels: 컴포넌트 관련 라벨

#39 Feature/cardlist
  public/images/Frame 2609920.png
  src/app/(home)/@createmodal/createmodal/page.tsx
  src/app/(home)/page.tsx
  src/app/components/DateBadge.tsx
  src/app/components/cardlist/Card.tsx
  src/app/components/cardlist/CardList.tsx
  tailwind.config.ts
Labels: 버그 관련 라벨, 스타일 관련 라벨, 컴포넌트 관련 라벨

#46 Feature/cardlist
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/_tests/Button.tsx
  src/app/_tests/Count.tsx
  src/app/_tests/Tag.tsx
  src/app/components/DateBadge.tsx
  src/app/components/Login.tsx
  src/app/components/PageInfo/PageInfo.tsx
  src/app/components/cardlist/Card.tsx
  src/app/components/cardlist/CardList.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#47 캘린더 color 커스텀 추가
  src/app/(auth)/login/page.tsx
  src/app/components/Calendar/Calender.tsx
  src/app/components/Calendar/CalenderTime.tsx
  src/app/globals.css
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#45 feat: 상세페이지 카드 디테일 컴포넌트 구현
  src/app/(home)/meeting/[id]/page.tsx
  src/app/components/MeetingCard.tsx
  src/app/types/meetingDetail.ts
Labels: 컴포넌트 관련 라벨

#53 feat: 공통 컴포넌트 Button 추가(state prop 전달 시 typescript 경고 버그 작업 중)
  src/app/(home)/mypage/page.tsx
  src/app/components/Button/Button.tsx
Labels: 컴포넌트 관련 라벨

#48 feat: deadline badge 구현
  src/app/(home)/meeting/[id]/page.tsx
  src/app/components/DeadlineBadge.tsx
Labels: 컴포넌트 관련 라벨

#54 모임 만들기 폼 컴포넌트 제작 및 UI 테스트
  next.config.ts
  src/app/(home)/@createmodal/createmodal/page.tsx
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/app/(home)/page.tsx
  src/app/_tests/Button.tsx
  src/app/_tests/Service.tsx
  src/app/components/Calendar/CalenderTime.tsx
  src/app/components/InputWindow.tsx
  src/app/hooks/useMeeting.tsx
  src/app/layout.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨, 페이지 단위 관련 라벨

#55 Feature/footer
  package-lock.json
  package.json
  src/app/(home)/meeting/[id]/page.tsx
  src/app/(home)/meeting/_components/footer.tsx
Labels: 컴포넌트 관련 라벨

#51 #fix: pageNavBar 수정
  constants/index.ts
  public/icons/dalaemfit.png
  public/icons/dalaemfit.svg
  public/icons/workation.png
  public/icons/workation.svg
  src/app/components/PageNav/PageNavButton.tsx
  src/app/components/PageNav/PageNavbar.tsx
Labels: 컴포넌트 관련 라벨

#50 feat: reviewCard 공통컴포넌트 구현
  src/app/components/ReviewCard/ReviewCard.tsx
Labels: 컴포넌트 관련 라벨

#63 Feature/create meeting form component
  src/app/(home)/@createmodal/createmodal/page.tsx
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/app/components/InputWindow.tsx
  src/app/hooks/useMeeting.tsx
Labels: 컴포넌트 관련 라벨

#73 fix: modal 오픈 시에 상단 스크롤 이동하는 버그 수정
  commitlint.config.js
  src/components/Modal/Modal.tsx
Labels: 버그 관련 라벨

#75 fix: 버튼 hover 색상 안바뀌는 현상, `isFull` prop 적용 안 되는 현상 수정
  commitlint.config.js
  src/app/globals.css
  src/components/Button/Button.tsx
Labels: 버그 관련 라벨

#76 feat: Members 공통 컴포넌트 정원 마감 시 하이라이팅 기능 여부 선택 옵션으로 변경
  src/app/(home)/mypage/page.tsx
  src/components/Members/Members.tsx
Labels: 컴포넌트 관련 라벨

#77 feat: HeartRatings 공통 컴포넌트 prop 변경(handleChange 핸들러 prop 추가)
  src/app/(home)/mypage/page.tsx
  src/components/HeartRatings/HeartRatings.tsx
  src/components/HeartRatings/HeartRatingsInteractive.tsx
Labels: 컴포넌트 관련 라벨

#79 Feature/cardlist
  commitlint.config.js
  src/components/MainCard/Card.tsx
Labels: 스타일 관련 라벨

#72 feat: filtering 공통컴포넌트 구현(NO CALENDAR VER.) + fix: 커밋린트 오류 수정
  public/icons/arrow/arrowDownDefault.png
  public/icons/arrow/arrowDownDefault.svg
  public/icons/sort/sortDefault.png
  public/icons/sort/sortDefault.svg
  src/app/(home)/all-reviews/page.tsx
  src/components/Filtering/Filter.tsx
  src/constants/index.ts
Labels: 버그 관련 라벨, 컴포넌트 관련 라벨

#84 Feature/calender
  src/app/components/Calendar/CalenderImage.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#80 Feature/create meeting form component
  commitlint.config.js
  next.config.ts
  src/api/meeting/createMeeting.ts
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/@createmodal/createmodal/page.tsx
  src/app/(home)/_components/Button.tsx
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/app/(home)/page.tsx
  src/components/Calendar/CalenderTime.tsx
  src/components/InputSection/InputWindow.tsx
  src/components/MainCard/Card.tsx
  src/components/MainCard/CardList.tsx
  src/components/Service/Service.tsx
  src/hooks/customs/useMeeting.tsx
  src/types/createMeetingType.ts
Labels: 컴포넌트 관련 라벨, api 관련 라벨

#83 Feature/detailpage pagination
  public/icons/arrow/arrow.svg
  public/icons/arrow/blackArrow.svg
  src/app/(home)/meeting/[id]/page.tsx
  src/app/(home)/meeting/_components/Pagination.tsx
  src/app/(home)/meeting/_components/footer.tsx
  src/types/paginationType.ts
Labels: 컴포넌트 관련 라벨

#89 style: 공통 레이아웃 작업(로그인, 회원가입, GNB)
  next.config.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/GNB/Header.tsx
Labels: 스타일 관련 라벨

#90 배포환경 테스트
  src/_tests/deployment.md
Labels: 배포 관련 라벨

#91 feat: datailpage API 연결
  src/api/detail-meeting/getDetailMeetingDate.ts
  src/app/(home)/meeting/[id]/page.tsx
  src/types/meetingDetail.ts
  src/types/paginationType.ts
Labels: api 관련 라벨

#96 feat: detailpage Review API 연결
  src/api/detail-meeting/getDetailReviewData.ts
  src/app/(home)/meeting/[id]/page.tsx
  src/types/paginationType.ts
Labels: api 관련 라벨

#85 feat: Button 공통 컴포넌트 변경(link 태그 대응, varataion prop 추가)
  src/app/(home)/mypage/page.tsx
  src/app/globals.css
  src/components/Button/Button.tsx
Labels: 컴포넌트 관련 라벨

#87 feat: 마이페이지 프로필 이미지 수정 기능 추가
  next.config.ts
  src/api/getUserData.ts
  src/api/users.ts
  src/app/(home)/mypage/@profile/(.)my-profile/page.tsx
  src/app/(home)/mypage/@profile/default.tsx
  src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
  src/app/(home)/mypage/components/ProfileForm/Input.tsx
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
  src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
  src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.tsx
  src/app/(home)/mypage/components/ProfileInput/ProfileInput.tsx
  src/app/(home)/mypage/layout.tsx
  src/app/(home)/mypage/my-profile/page.tsx
  src/app/(home)/mypage/page.tsx
  src/types/userType.ts
Labels: 컴포넌트 관련 라벨, api 관련 라벨

#99 fix: 빌드 오류 수정
  src/app/(home)/mypage/@profile/(.)my-profile/page.tsx
  src/app/(home)/mypage/@review/(..)mypage/create-review/[id]/page.tsx
  src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.tsx
  src/components/Modal/Modal.tsx
  src/lib/ModalProvider.tsx
Labels: 버그 관련 라벨, 배포 관련 라벨

#94 feat: filtering 컴포넌트 수정
  src/app/(home)/all-reviews/page.tsx
  src/app/components/Calendar/CalenderImage.tsx
  src/components/Filtering/FIlterList.tsx
  src/components/Filtering/Filter.tsx
Labels: 컴포넌트 관련 라벨

#95 style: 모임 만들기 폼 컴포넌트 반응형 UI 수정 중
  src/api/meeting/createMeeting.ts
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/@createmodal/createmodal/page.tsx
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/app/(home)/_components/FilterInput.tsx
  src/app/(home)/_components/FilterInputList.tsx
  src/app/(home)/all-reviews/page.tsx
  src/app/(home)/page.tsx
  src/components/Calendar/CalenderImage (1).tsx
  src/components/Filtering/FIlterList.tsx
  src/components/Filtering/Filter.tsx
  src/components/Service/Service.tsx
Labels: 스타일 관련 라벨

#104 feat: detail review 공통 컴포넌트로 변경
  src/api/detail-meeting/getDetailMeetingDate.ts
  src/api/detail-meeting/getDetailReviewData.ts
  src/app/(home)/meeting/[id]/page.tsx
  src/app/(home)/meeting/_components/Pagination.tsx
Labels: 컴포넌트 관련 라벨

#105 Feature/create meeting form component
  src/_tests/deployment.md
  src/api/meeting/getMeetingDate.ts
Labels: 배포 관련 라벨

#109 채은님이 만든 필터링 컴포넌트 적용 후 필터링 기능 구현
  src/app/(home)/_components/HomeFilter.tsx
  src/app/(home)/page.tsx
  src/components/MainCard/CardList.tsx
  src/store/useInputSelectFilterStore.tsx
Labels: 컴포넌트 관련 라벨, zustand 관련 라벨, 페이지 단위 관련 라벨, 리팩토링

#112 feat: 모임 목록 get 요청 부분 공통 함수화 적용
  src/api/meeting/getMeetingDate.ts
  src/components/MainCard/CardList.tsx
  src/hooks/customs/useMainCard.ts
  src/types/createMeetingType.ts
  src/types/meetingsType.ts
Labels: api 관련 라벨

#113 feat: 좋아요 버튼 회원원ID zustand에서 관리
  src/app/(home)/meeting/_components/footer.tsx
  src/components/Button/LikeButton.tsx
  src/hooks/customs/useLike.ts
  src/lib/likeStorage.ts
Labels: zustand 관련 라벨

#114 dateBadge button태그 span태그로 변경
  src/components/Badge/DateBadge.tsx
Labels: 스타일 관련 라벨

#116 develop 브랜치 pull 작업
  public/icons/profileDefault.svg
  src/api/detail-meeting/getDetailMeetingDate.ts
  src/api/detail-meeting/getDetailReviewData.ts
  src/api/getAttendee.ts
  src/api/getReveiwScore.ts
  src/api/getUserData.ts
  src/api/meeting/getMeetingDate.ts
  src/api/userAuth.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(home)/_components/FilterInput.tsx
  src/app/(home)/_components/FilterInputList.tsx
  src/app/(home)/_components/HomeFilter.tsx
  src/app/(home)/all-reviews/_components/reviewScores.tsx
  src/app/(home)/all-reviews/page.tsx
  src/app/(home)/meeting/[id]/page.tsx
  src/app/(home)/meeting/_components/AttendeeProfiles.tsx
  src/app/(home)/meeting/_components/MeetingCard.tsx
  src/app/(home)/meeting/_components/Pagination.tsx
  src/app/(home)/meeting/_components/footer.tsx
  src/app/(home)/page.tsx
  src/components/Badge/DateBadge.tsx
  src/components/Button/LikeButton.tsx
  src/components/GNB/Header.tsx
  src/components/InputSection/HideToggleButton.tsx
  src/components/InputSection/InputWindow.tsx
  src/components/InputSection/Selectbox.tsx
  src/components/Login/Login.tsx
  src/components/MainCard/Card.tsx
  src/components/MainCard/CardList.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/components/Signup/Signup.tsx
  src/components/Signup/SignupInputSection.tsx
  src/constants/index.ts
  src/hooks/customs/useLike.ts
  src/hooks/customs/useMainCard.ts
  src/lib/likeStorage.ts
  src/store/useAuthStore.tsx
  src/store/useInputSelectFilterStore.tsx
  src/types/createMeetingType.ts
  src/types/meetingsType.ts
  src/types/pageComponentType.ts
  src/types/reviewType.ts
  src/types/userType.ts
Labels: develop branch pull 작업 관련 라벨

#115 develop 브랜치 pull 작업
  src/components/MainCard/Card.tsx
Labels: develop branch pull 작업 관련 라벨

#118 feat: detail page footer 참가자 api 연결
  src/api/detail-meeting/joinGroup.ts
  src/app/(home)/meeting/_components/footer.tsx
Labels: api 관련 라벨

#120 feat: API 공통화 작업
  src/api/detail-meeting/getDetailReviewData.ts
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/meeting/[id]/page.tsx
  src/service/reviewService.ts
  src/types/reviewType.ts
Labels: api 관련 라벨

#121 모임 만들기 폼 수정
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/app/(home)/_components/FilterInput.tsx
  src/app/(home)/_components/FilterInputList.tsx
  src/app/(home)/_components/HomeButton.tsx
  src/app/(home)/_components/HomeFilter.tsx
  src/app/(home)/page.tsx
  src/components/InputSection/Selectbox.tsx
  src/hooks/customs/useMeeting.tsx
Labels: 버그 관련 라벨, 컴포넌트 관련 라벨, 리팩토링

#124 비회원시 로그인하라는 기능 추가 및 api 공통 로직 적용
  src/app/(home)/_components/HomeButton.tsx
  src/app/(home)/mypage/components/CardList/CardBase.tsx
  src/app/(home)/mypage/page.tsx
  src/components/MainCard/CardList.tsx
  src/hooks/customs/useMainCard.ts
Labels: api 관련 라벨, 페이지 단위 관련 라벨, 리팩토링

#126 feat: 모임 참여하기 관련 데이터 카드 컴포넌트에 적용 및 마감 모임 표시 추가
  src/app/(home)/_components/HomeFilter.tsx
  src/components/MainCard/Card.tsx
  src/components/MainCard/CardList.tsx
Labels: 컴포넌트 관련 라벨, api 관련 라벨, 페이지 단위 관련 라벨

#128 footer api 연결
  package-lock.json
  package.json
  src/api/detail-meeting/cancelGroup.ts
  src/api/detail-meeting/participantsGroup.ts
  src/app/(home)/meeting/[id]/page.tsx
  src/app/(home)/meeting/_components/footer.tsx
Labels: api 관련 라벨

#130 카드 컴포넌트 모집 인원 마감에 따라 UI 및 기능 추가
  src/components/Button/LikeButton.tsx
  src/components/MainCard/Card.tsx
  src/components/MainCard/CardList.tsx
  src/types/likeButtonType.ts
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨, 페이지 단위 관련 라벨, 리팩토링

#131 feat: 카드 디테일 컴포넌트 조합
  src/app/(home)/meeting/[id]/page.tsx
  src/app/(home)/meeting/_components/MeetingCard.tsx
  src/app/(home)/meeting/_components/footer.tsx
  src/types/meetingDetail.ts
Labels: 컴포넌트 관련 라벨

#140 fix: useEffect 제거
  cody.json
  package-lock.json
  package.json
  src/components/MainCard/CardList.tsx
  src/hooks/customs/useMainCard.ts
  src/hooks/customs/useMeeting.tsx
Labels: 컴포넌트 관련 라벨

#136 feat: 모든 리뷰 관련 api추가 및 컴포넌트 구현
  src/api/getReveiwScore.ts
  src/app/(home)/all-reviews/_components/ReviewCardList.tsx
  src/app/(home)/all-reviews/_components/ReviewSummary.tsx
  src/app/(home)/all-reviews/page.tsx
  src/hooks/customs/useFetchReviews.tsx
  src/hooks/query/useFetchReviewsScore.tsx
  src/store/useInputSelectFilterStore.tsx
  src/types/reviewType.ts
Labels: 컴포넌트 관련 라벨, api 관련 라벨, 페이지 단위 관련 라벨

#137 fix: 찜한 모임 페이지 오류 수정
  src/app/(home)/favorite-meetings/meetingService.tsx
  src/components/MainCard/CardList.tsx
  src/hooks/customs/useMainCard.ts
Labels: 버그 관련 라벨, api 관련 라벨

#143 refactor: footer 컴포넌트 로직 세분화
  src/app/(home)/meeting/_components/footer.tsx
  src/hooks/customs/useGroupActions.ts
Labels: 리팩토링

#142 feat: filtering state 관련 Context API 추가 및 기존 코드 Context API에 맞게 변경
  src/app/(home)/_components/HomeFilter.tsx
  src/app/(home)/all-reviews/page.tsx
  src/app/(home)/page.tsx
  src/components/Filtering/FIlterList.tsx
  src/components/PageNav/PageNavbar.tsx
  src/context/FilterContent.tsx
  src/hooks/customs/useFetchReviews.tsx
  src/hooks/customs/useFilter.tsx
  src/hooks/query/useFetchReviewsScore.tsx
  src/types/filterType.ts
  src/types/reviewType.ts
Labels: 컴포넌트 관련 라벨, 페이지 단위 관련 라벨, 리팩토링

#144 feat: 찜한 모임 카드리스트 hook 분리
  src/app/(home)/favorite-meetings/components/CardList/CardList.tsx
  src/app/(home)/favorite-meetings/page.tsx
  src/hooks/customs/useFavoriteMeetings.tsx
Labels: 컴포넌트 관련 라벨

#146 feat: 찜한 모임 알림 뱃지 상태 관리 useNotificationStore 추가
  src/hooks/customs/useLikeNotify.tsx
  src/store/useNotificationStore.tsx
Labels: zustand 관련 라벨

#148 feat: ReviewCard 내용 형식에 맞게 변경 + style: ReviewCard, Filter 컴포넌트 css 변경
  src/components/Filtering/Filter.tsx
  src/components/ReviewCard/ReviewCard.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#147 feat: 마이페이지 모임 참여 취소 기능 추가
  src/app/(home)/mypage/components/CardList/CardBase.tsx
  src/app/(home)/mypage/components/CardList/CardInfo.tsx
  src/app/(home)/mypage/components/CardList/CardList.tsx
  src/app/(home)/mypage/components/CardList/CreateReviewButton.tsx
  src/app/(home)/mypage/createdMeetings/page.tsx
  src/app/(home)/mypage/page.tsx
  src/hooks/customs/useMyMeetings.tsx
Labels: 컴포넌트 관련 라벨, api 관련 라벨

#145 feat: react-query infinite 무한 스크롤 기능 도입 및 후처리 추가
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/page.tsx
  src/components/MainCard/CardListInfinite.tsx
  src/hooks/customs/useMainCard.ts
  src/hooks/query/useHomeMeetingCardList.ts
Labels: 컴포넌트 관련 라벨, api 관련 라벨, react-query 관련 라벨, 페이지 단위 관련 라벨, 리팩토링

#151 feat: staleTime, gcTime 변경 및 카드 제목 수정
  src/components/MainCard/CardListInfinite.tsx
  src/lib/ReactQueryProvider.tsx
Labels: 컴포넌트 관련 라벨, 리팩토링

#152 feat: 모임 주최자가 모임을 만드는 동시에 자동 참여하는 로직 추가
  src/api/meeting/createMeeting.ts
  src/app/(home)/_components/CreateMeetingForm.tsx
Labels: 컴포넌트 관련 라벨, api 관련 라벨, 페이지 단위 관련 라벨

#154 feat: useLikeNotify hook 에서 찜한 개수 바로 불러올 수 있도록 상태 추가
  src/hooks/customs/useLikeNotify.tsx
Labels: zustand 관련 라벨

#159 style: 공통 컴포넌트 Badge css 변경
  src/components/Badge/Badge.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#153 feat: 찜한 모임에서 찜하기 취소 시 아이템 삭제 기능 추가(+ 모임 제목 출력)
  src/app/(home)/favorite-meetings/components/CardList/CardList.tsx
  src/hooks/customs/useFavoriteMeetings.tsx
Labels: api 관련 라벨

#158 feat: detail page react-query 적용
  src/app/(home)/meeting/[id]/page.tsx
  src/app/(home)/meeting/_components/MeetingCard.tsx
  src/hooks/query/useDetailMeetingData.ts
  src/hooks/query/useDetailReviewData.ts
Labels: react-query 관련 라벨

#161 style: 공통 레이아웃 설정
  src/app/(home)/layout.tsx
Labels: 스타일 관련 라벨

#160 fix: 모든 리뷰 페이지에서 공통 컴포넌트 ProgressBar 에 평균 평점 수치 적용 안되는 현상 수정
  src/components/ProgressBar/ProgressBar.tsx
Labels: 버그 관련 라벨, 컴포넌트 관련 라벨

#156 feat: 찜한 모임 페이지 모임 종류 필터링 추가
  src/app/(home)/favorite-meetings/layout.tsx
  src/hooks/customs/useFavoriteMeetings.tsx
Labels: 페이지 단위 관련 라벨

#164 fix: 프로필 사진 없을 시 프로필 폼 진입 오류 수정
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
Labels: 버그 관련 라벨

#162 style: 마이페이지 예약 취소 confirm 모달 버튼 UI 변경
  src/components/Dialog/Dialog.tsx
Labels: 스타일 관련 라벨

#163 fix: 초기 페이지 설정 값, limit 값, api 호출 콘솔추가
  src/api/meeting/getMeetingDate.ts
  src/components/MainCard/CardListInfinite.tsx
  src/hooks/query/useHomeMeetingCardList.ts
Labels: 컴포넌트 관련 라벨

#166 fix: 로그인 유지 안되는 문제 해결
  src/components/Login/Login.tsx
Labels: 버그 관련 라벨

#168 feat: 모임 생성하기 -> react mutation 로직 수정 및 새로고침 이슈 해결
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/hooks/mutation/useCreateMeeting.ts
Labels: api 관련 라벨, react-query 관련 라벨, 페이지 단위 관련 라벨, 리팩토링

#169 feat: 모임 생성 시 성공 알림 추가로 UX 향상
  package-lock.json
  package.json
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/layout.tsx
  src/hooks/mutation/useCreateMeeting.ts
  src/hooks/query/useHomeMeetingCardList.ts
Labels: react-query 관련 라벨, 페이지 단위 관련 라벨

#167 feat:status badge 조건 추가
  src/app/(home)/favorite-meetings/components/CardList/CardList.tsx
  src/app/(home)/meeting/_components/MeetingCard.tsx
  src/components/Badge/StatusBadge.tsx
  src/components/MainCard/CardList.tsx
  src/components/MainCard/CardListInfinite.tsx
Labels: 컴포넌트 관련 라벨

#165 feat: 모든 리뷰 관련 react-query 추가 및 리뷰 평점 로직 수정
  src/api/getReveiwScore.ts
  src/app/(home)/all-reviews/_components/ReviewSummary.tsx
  src/app/(home)/all-reviews/page.tsx
  src/constants/index.ts
  src/hooks/customs/useFetchReviews.tsx
  src/hooks/query/useFetchReviewData.tsx
  src/hooks/query/useFetchReviewsScore.tsx
  src/types/reviewType.ts
Labels: api 관련 라벨, react-query 관련 라벨, 페이지 단위 관련 라벨

#173 style: 로그인, 회원가입 레이아웃 변경
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/GNB/Header.tsx
  src/components/Login/Login.tsx
  src/components/Signup/Signup.tsx
Labels: 스타일 관련 라벨

#171 feat: 로그아웃 시 알림 뱃지 초기화 기능 추가
  src/hooks/customs/useAuth.tsx
  src/store/useNotificationStore.tsx
Labels: zustand 관련 라벨

#172 feat: 로컬 스토리지 util 함수 추가
  src/app/(home)/favorite-meetings/meetingService.tsx
  src/hooks/customs/useFavoriteMeetings.tsx
  src/hooks/customs/useLikeNotify.tsx
  src/types/likeButtonType.ts
  src/utils/localStorage.ts
Labels: api 관련 라벨

#176 feat: footer react-query 도입
  src/app/(home)/meeting/_components/footer.tsx
  src/hooks/customs/useGroupActions.ts
  src/hooks/mutation/useGroupMutations.ts
Labels: react-query 관련 라벨

#175 fix: 패럴렐 라우트 동작 시 모임 목록 안보이는 현상 해결
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/components/MainCard/CardListInfinite.tsx
  src/constants/index.ts
  src/hooks/query/useHomeMeetingCardList.ts
Labels: 버그 관련 라벨, react-query 관련 라벨, 페이지 단위 관련 라벨

#174 fix: 찜한 모임 개수 알림 뱃지 반영 안되는 현상 수정(찜한 모임 개수 알림 뱃지 동기화 로직 변경)
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/favorite-meetings/meetingService.tsx
  src/hooks/customs/useFavoriteMeetings.tsx
  src/hooks/customs/useLikeNotify.tsx
Labels: 버그 관련 라벨
