Repository junesung1004/dallaem, pull requests merged in 2025-03, with the labels that each got.

#179 fix: 리뷰 작성 POST 요청 안 되는 버그 수정
  src/api/reivews.ts
Labels: 버그 관련 라벨

#181 style: tailwind config 에 추가된 대표 컬러로 수정
  src/_tests/Tag.tsx
  src/app/(home)/_components/Button.tsx
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/app/(home)/meeting/_components/MeetingCard.tsx
  src/app/(home)/meeting/_components/footer.tsx
  src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
  src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
  src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
  src/app/(home)/mypage/components/Tag/TagBase.tsx
  src/app/globals.css
  src/components/Badge/DateBadge.tsx
  src/components/Badge/DeadlineBadge.tsx
  src/components/Badge/StatusBadge.tsx
  src/components/Button/Button.tsx
  src/components/Filtering/FilterDropdown.tsx
  src/components/HeartRatings/Heart.tsx
  src/components/InputSection/InputWindow.tsx
  src/components/Login/Login.tsx
  src/components/MainCard/Card.tsx
  src/components/Members/Members.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/components/Service/Service.tsx
  src/components/Signup/Signup.tsx
Labels: 스타일 관련 라벨

#180 style: tailwind config color 디자인 토큰 추가
  src/_tests/Tag.tsx
  src/app/(home)/_components/Button.tsx
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/app/(home)/meeting/_components/MeetingCard.tsx
  src/app/(home)/meeting/_components/footer.tsx
  src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
  src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
  src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
  src/app/(home)/mypage/components/Tag/TagBase.tsx
  src/app/globals.css
  src/components/Badge/DateBadge.tsx
  src/components/Badge/DeadlineBadge.tsx
  src/components/Badge/StatusBadge.tsx
  src/components/Button/Button.tsx
  src/components/Filtering/FilterDropdown.tsx
  src/components/HeartRatings/Heart.tsx
  src/components/InputSection/InputWindow.tsx
  src/components/Login/Login.tsx
  src/components/MainCard/Card.tsx
  src/components/Members/Members.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/components/Service/Service.tsx
  src/components/Signup/Signup.tsx
  tailwind.config.ts
Labels: 스타일 관련 라벨

#182 style: 헤더 배경색 그라데이션으로 변경
  src/components/GNB/Header.tsx
Labels: 스타일 관련 라벨

#186 fix: 필터링 캘린더 수정
  src/app/globals.css
  src/components/Calendar/CalendarFilter.tsx
  src/components/Calendar/Calender.tsx
Labels: 버그 관련 라벨, 스타일 관련 라벨

#193 fix: 캘린더 수정 및, 메인 카드 수정
  package-lock.json
  src/app/(home)/@createmodal/createmodal/page.tsx
  src/app/(home)/_components/CreateMeetingForm.tsx
  src/components/Badge/DeadlineBadge.tsx
  src/components/Calendar/CalenderTime.tsx
  src/components/MainCard/Card.tsx
  src/components/MainCard/CardListInfinite.tsx
  src/components/Members/Members.tsx
  src/hooks/customs/useMeeting.tsx
  yarn.lock
Labels: 버그 관련 라벨, 리팩토링

#187 fix: 마이페이지 데이터 없을 때 UI 처리
  src/app/(home)/mypage/components/CardList/CardList.tsx
  src/app/(home)/mypage/createdMeetings/page.tsx
  src/app/(home)/mypage/loading.tsx
  src/app/(home)/mypage/meetings/page.tsx
  src/app/(home)/mypage/page.tsx
  src/app/(home)/mypage/reviews/page.tsx
  src/app/(home)/mypage/reviews/writable/page.tsx
  src/app/(home)/mypage/reviews/written/page.tsx
Labels: 버그 관련 라벨, 페이지 단위 관련 라벨

#189 fix: 리뷰 생성 POST 요청 시 특정 모임 id로만 작성 요청하던 현상 수정
  src/app/(home)/mypage/components/CardList/CardBase.tsx
  src/app/(home)/mypage/components/CardList/CreateReviewButton.tsx
Labels: 버그 관련 라벨

#191 feat: 마이페이지 참여 시간이 지나지 않은 아이템이 상단에 보여지도록 변경
  src/app/(home)/mypage/components/CardList/CardBase.tsx
  src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
  src/hooks/customs/useMyMeetings.tsx
  src/types/meetingsType.ts
Labels: 컴포넌트 관련 라벨

#196 feat: 마이페이지 리액트 쿼리 적용
  src/app/(home)/mypage/components/CardList/CardBase.tsx
  src/app/(home)/mypage/components/CardList/CardList.tsx
  src/app/(home)/mypage/components/CardList/CreateReviewButton.tsx
  src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
  src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
  src/app/(home)/mypage/createdMeetings/page.tsx
  src/app/(home)/mypage/loading.tsx
  src/app/(home)/mypage/meetings/page.tsx
  src/app/(home)/mypage/page.tsx
  src/app/(home)/mypage/reviews/page.tsx
  src/app/(home)/mypage/reviews/writable/page.tsx
  src/app/(home)/mypage/reviews/written/page.tsx
  src/hooks/customs/useMyMeetings.tsx
  src/types/meetingsType.ts
Labels: react-query 관련 라벨

#192 feat: QA 관련 필터링 기능 추가
  src/components/Filtering/FIlterList.tsx
  src/components/Filtering/FilterDropdown.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#195 fix: 마이페이지-리뷰-서브아이템 선택안되는 문제 해결
  src/components/PageNav/PageNavbar.tsx
Labels: 버그 관련 라벨

#197 feat: Button 컴포넌트 사용
  src/app/(home)/meeting/_components/footer.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#198 feat: 종료 이후엔 footer 비활성화
  src/app/(home)/meeting/[id]/page.tsx
Labels: 컴포넌트 관련 라벨

#201 모든 리뷰 페이지 무한 스크롤 구현
  src/app/(home)/all-reviews/ReviewsPage.tsx
  src/app/(home)/all-reviews/_components/ReviewCardList.tsx
  src/app/(home)/all-reviews/_components/ReviewSummary.tsx
  src/app/(home)/all-reviews/page.tsx
  src/hooks/query/useFetchReviewData.tsx
  src/service/reviewService.ts
Labels: 컴포넌트 관련 라벨, api 관련 라벨, react-query 관련 라벨, 페이지 단위 관련 라벨

#199 feat: heart 애니메이션 추가
  src/components/Button/LikeButton.tsx
  tailwind.config.ts
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨, config 관련 라벨

#200 fix: 사용자가 이미 리뷰를 작성한 모임에 리뷰를 추가할 시 예외 처리
  src/api/reivews.ts
  src/hooks/customs/useCreateReview.tsx
Labels: 버그 관련 라벨

#202 fix: 헤더 드롭다운 z-index 추가
  src/components/GNB/ProfileTooltip.tsx
Labels: 스타일 관련 라벨

#213 fix: 프로필 수정시 헤더에도 적용되게 임시 적용
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
  src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
  src/components/GNB/ProfileTooltip.tsx
Labels: 버그 관련 라벨

#211 style: 무한 스크롤 적용 후 모든 리뷰카드 반응형 깨짐 css 수정
  src/app/(home)/all-reviews/ReviewsPage.tsx
  src/app/(home)/all-reviews/_components/ReviewCardList.tsx
  src/components/ReviewCard/ReviewCard.tsx
Labels: 스타일 관련 라벨

#210 fix: 찜한 모임 가져오는 쿼리에 enabled 속성 추가
  src/hooks/customs/useFavoriteMeetings.tsx
Labels: react-query 관련 라벨

#209 fix: 찜한 모임 데이터 없을 때 UI 처리
  src/app/(home)/favorite-meetings/components/CardList/CardList.tsx
  src/app/(home)/favorite-meetings/layout.tsx
Labels: 스타일 관련 라벨

#224 fix: 프로필사진 없을경우 헤더에 프로필이 안 보이는 현상 해결
  src/components/GNB/ProfileTooltip.tsx
Labels: 버그 관련 라벨

#225 refator: 프로필 수정 시 바로 헤더에 적용되도록 전역 변수 사용
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
  src/app/(home)/mypage/components/ProfileHeader/ProfileHeader.tsx
  src/app/(home)/mypage/components/ProfileInput/ProfileInput.tsx
  src/components/GNB/ProfileTooltip.tsx
  src/store/useAuthStore.tsx
Labels: 버그 관련 라벨, zustand 관련 라벨, 리팩토링

#219 refactor: 리뷰 평점 리팩토링 (기획상의 변경)
  src/api/getReveiwScore.ts
  src/app/(home)/all-reviews/_components/ReviewSummary.tsx
  src/hooks/query/useFetchReviewsScore.tsx
Labels: 리팩토링

#221 config: Jest가 절대경로 인식하도록 함
  jest.config.ts
Labels: config 관련 라벨

#229 refactor: 모든 리뷰 리뷰 초기 데이터 SSR (218번 이슈 새로운 브랜치에서 배포 테스트)
  src/app/(home)/all-reviews/ReviewsPage.tsx
  src/app/(home)/all-reviews/page.tsx
  src/context/FilterContent.tsx
  src/hooks/query/useFetchReviewData.tsx
  src/service/reviewService.ts
  src/types/reviewType.ts
Labels: 버그 관련 라벨, react-query 관련 라벨, 리팩토링

#230 fix: 모든 리뷰 페이지 인원 비율 progressbar 진행도에 반영 안되는 현상 수정
  src/components/ProgressBar/ProgressBar.tsx
Labels: 버그 관련 라벨, 컴포넌트 관련 라벨

#237 fix: workflow yml 수정
  .github/workflows/main.yml
Labels: 버그 관련 라벨, config 관련 라벨, 배포 관련 라벨

#238 style: input 창 스타일 변경
  src/components/InputSection/InputWindow.tsx
Labels: 스타일 관련 라벨

#222 refactor: 메인 모임 목록 데이터 패칭 csr ssr 수정
  .github/workflows/main.yml
  src/_tests/deployment.md
  src/api/meeting/getMeetingDate.ts
  src/app/(home)/MainPage.tsx
  src/app/(home)/_components/HomeButton.test.tsx
  src/app/(home)/favorite-meetings/components/CardList/CardList.tsx
  src/app/(home)/page.tsx
  src/components/Filtering/FIlterList.tsx
  src/components/MainCard/Card.tsx
  src/components/MainCard/CardList.tsx
  src/components/MainCard/CardListInfinite.tsx
  src/components/PageNav/PageNavbar.tsx
  src/hooks/mutation/useCreateMeeting.ts
  src/hooks/query/useHomeMeetingCardList.ts
  src/types/filterType.ts
Labels: api 관련 라벨, 페이지 단위 관련 라벨, 리팩토링

#243 config: 코드커브 커버리지 수치 조절
  codecov.yml
  src/_tests/deployment.md
Labels: config 관련 라벨

#244 feat: 테스트 코드 초기 설정 및 기본작업 추가
  src/app/(home)/_components/HomeButton.test.tsx
Labels: config 관련 라벨, 테스트 코드 작업 라벨

#242 fix: 모든 리뷰 카드 리스트 관련 코드 수정(로딩상태 추가, limit 값 수정)
  src/app/(home)/all-reviews/_components/ReviewCardList.tsx
Labels: 버그 관련 라벨, react-query 관련 라벨

#245 feat: 필터링 커스텀 훅, 타입 추가
  src/components/Filtering/FIlterListCustom.tsx
  src/components/PageNav/PageNavbarCustom.tsx
  src/hooks/customs/useFilters.tsx
  src/types/filterType.ts
Labels: 리팩토링

#240 fix: 로그아웃 시 라우팅 페이지 변경
  src/hooks/customs/useAuth.tsx
Labels: 버그 관련 라벨

#239 refactor: user 전역상태변수에 setState 추가 및 활용
  src/api/getUserData.ts
  src/components/Login/Login.tsx
  src/hooks/customs/useAuth.tsx
  src/store/useAuthStore.tsx
  src/types/userType.ts
Labels: 리팩토링

#252 reafactor: 리뷰 작성 관련 에러 공통화
  src/components/Modal/ErrorModalContent.tsx
  src/hooks/customs/useErrorHandler.tsx
  src/lib/ReactQueryProvider.tsx
Labels: react-query 관련 라벨, 리팩토링

#247 refactor: 마이페이지 SSR 전환
  src/api/getUserData.ts
  src/api/meeting/myMeeting.ts
  src/api/userAuth.ts
  src/api/users.ts
  src/app/(auth)/api/route.ts
  src/app/(home)/mypage/components/CardList/CardList.tsx
  src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
  src/app/(home)/mypage/createdMeetings/page.tsx
  src/app/(home)/mypage/meetings/page.tsx
  src/app/(home)/mypage/page.tsx
  src/app/(home)/mypage/reviews/page.tsx
  src/app/(home)/mypage/reviews/writable/page.tsx
  src/app/(home)/mypage/reviews/written/components/CardList.tsx
  src/app/(home)/mypage/reviews/written/page.tsx
  src/middleware.ts
  src/types/reviewType.ts
Labels: 페이지 단위 관련 라벨, 리팩토링

#249 [BR7-379] fix: mutation 적용하여 리뷰 작성 후 새로고침 안 되는 버그 수정
  src/app/(home)/mypage/components/CardList/CardList.tsx
  src/app/(home)/mypage/components/CardList/Services/myMeetingService.ts
  src/app/(home)/mypage/components/ReviewForm/ReviewForm.tsx
  src/app/(home)/mypage/reviews/written/components/CardList.tsx
  src/hooks/customs/useCreateReview.tsx
  src/hooks/customs/useMyMeetings.tsx
  src/hooks/mutation/useReviewMutation.tsx
Labels: 버그 관련 라벨, react-query 관련 라벨, 리팩토링

#253 refactor: 예약 취소 기능 custom hook에서 분리하고 컴포넌트로 종속
  src/app/(home)/mypage/components/CardList/CardList.tsx
Labels: 컴포넌트 관련 라벨, 리팩토링

#251 fix: 초기데이터 필터 타입 누락 수정
  src/app/(home)/all-reviews/page.tsx
Labels: 버그 관련 라벨

#255 refactor: use filter custom hook 변경 반영
  src/app/(home)/favorite-meetings/components/CardList.tsx
  src/app/(home)/favorite-meetings/components/PageContent.tsx
  src/app/(home)/favorite-meetings/layout.tsx
  src/app/(home)/favorite-meetings/page.tsx
  src/hooks/customs/useFavoriteMeetings.tsx
Labels: 페이지 단위 관련 라벨, 리팩토링

#254 style: 모든 리뷰 페이지 style 변경 및 더보기 추가
  src/components/ReviewCard/ReviewCard.tsx
Labels: 스타일 관련 라벨, 컴포넌트 관련 라벨

#246 refactor: 모든 리뷰 페이지 필터링 방식 변경에 따른 코드 변경
  src/app/(home)/all-reviews/ReviewsPage.tsx
  src/app/(home)/all-reviews/_components/ReviewCardList.tsx
  src/app/(home)/all-reviews/_components/ReviewSummary.tsx
  src/app/(home)/all-reviews/page.tsx
  src/hooks/query/useFetchReviewData.tsx
  src/hooks/query/useFetchReviewsScore.tsx
Labels: react-query 관련 라벨, 리팩토링

#256 feat: 프로필 툴팁 외부 클릭시 사라지도록 함
  src/components/GNB/ProfileTooltip.tsx
Labels: 리팩토링

#257 fix: 로그인시 프로필 이미지 불러오지 않는 오류 해결
  src/components/Login/Login.tsx
Labels: 버그 관련 라벨

#263 Style: 서비스 기획 따른 텍스트 변경
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(home)/mypage/reviews/written/components/CardList.tsx
  src/app/layout.tsx
  src/components/GNB/Header.tsx
  src/components/Login/Login.tsx
  src/components/MainCard/CardList.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/components/Service/Service.tsx
  src/constants/index.ts
Labels: 스타일 관련 라벨

#267 docs: 리드미 작성 중
  README.md
  public/movies/유저 플로우 차트.jpg
  public/movies/화면 흐름도.jpg
Labels: 문서 작업 관련 라벨

#268 docs: 리드미 목록 리스트 설정 테스트
  README.md
Labels: 문서 작업 관련 라벨

#258 fix: 로그인 실패 시 에러 메시지 출력 안 되는 버그 수정
  src/api/userAuth.ts
  src/app/(auth)/api/route.ts
  src/hooks/customs/useAuth.tsx
Labels: 버그 관련 라벨, api 관련 라벨

#217 feat: paricipants-reactquery
  src/app/(home)/meeting/_components/footer.tsx
  src/hooks/query/useParticipantsData.ts
Labels: api 관련 라벨, react-query 관련 라벨, 리팩토링

#259 fix: 기획에 맞춰 디테일페이지 수정
  src/app/(home)/meeting/[id]/DetailClient.tsx
  src/app/(home)/meeting/[id]/ReviewClient.tsx
  src/app/(home)/meeting/_components/MeetingCard.tsx
  src/types/meetingDetail.ts
Labels: 컴포넌트 관련 라벨

#276 fix: 찜하기 버튼 클릭 시 디테일 페이지로 이동 오류 코드 수정
  src/components/Button/LikeButton.tsx
Labels: 버그 관련 라벨

#269 리드미 목차 이동 수정
  README.md
Labels: 문서 작업 관련 라벨

#278 feat: 번들 확인 라이브러리 설치
  next.config.ts
  package-lock.json
  package.json
Labels: config 관련 라벨

#283 docs: readme 수정
  Frame 1244830710.png
  README.md
  public/movies/Frame 1244830710.png
Labels: 문서 작업 관련 라벨

#279 test: filterList 관련 테스트 코드 작성
  src/components/Filtering/__tests__/FilterDropdown.test.tsx
  src/components/Filtering/__tests__/FilterListCustom.test.tsx
Labels: 테스트 코드 작업 라벨

#275 test: pageNavbar 테스트 코드
  src/components/PageNav/__tests__/PageNavbarCustom.test.tsx
Labels: 테스트 코드 작업 라벨

#273 test: 메인 홈페이지- 모임 만들기 버튼 컴포넌트 관련 테스트 코드
  src/app/(home)/_components/HomeButton.test.tsx
Labels: 테스트 코드 작업 라벨

#280 test: 모임 만들기 테스트코드
  src/app/(home)/_components/CreateMeetingForm.test.tsx
Labels: 테스트 코드 작업 라벨

#271 test: 로그인 테스트 코드
  src/components/InputSection/HideToggleButton.tsx
  src/components/Login/Login.activeButton.test.tsx
  src/components/Login/Login.hideToggleButton.test.tsx
  src/components/Login/Login.onBlur.test.tsx
  src/components/Login/Login.onFocus.test.tsx
  src/components/Login/Login.onSubmit.test.tsx
  src/components/Login/Login.tsx
Labels: 테스트 코드 작업 라벨

#272 test: 회원가입 테스트코드
  src/components/Signup/Signup.onBlur.test.tsx
  src/components/Signup/Signup.onFocus.test.tsx
  src/components/Signup/Signup.tsx
Labels: 테스트 코드 작업 라벨

#265 test: 프로필 폼 테스트 코드 작성
  src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.test.tsx
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
  src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.test.tsx
  src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.tsx
Labels: 테스트 코드 작업 라벨

#274 test: useFilters 테스트 코드 작성
  src/hooks/customs/__tests__/useFilters.test.ts
Labels: 테스트 코드 작업 라벨

#266 fix: 리뷰 날짜 필터링 코드 수정 (재수정)
  src/app/(home)/all-reviews/_components/ReviewCardList.tsx
  src/components/ReviewCard/ReviewCard.tsx
Labels: 버그 관련 라벨, 컴포넌트 관련 라벨

#286 test: footer component test code
  src/app/(home)/meeting/_components/footer.test.tsx
Labels: 테스트 코드 작업 라벨

#288 test: pagination test code
  src/app/(home)/meeting/_components/pagination.test.tsx
Labels: 테스트 코드 작업 라벨

#289 develop 브랜치 -> main 브랜치로 머지 후 배포
  public/images/logo/logo.png
  public/images/logo/logoLarge.png
  public/images/logo/logoSmall.png
  public/images/logo/madal.png
  public/manifest.json
  src/app/(home)/_components/CreateMeetingForm.test.tsx
  src/app/(home)/_components/HomeButton.test.tsx
  src/app/(home)/all-reviews/_components/ReviewCardList.tsx
  src/app/(home)/meeting/[id]/DetailClient.tsx
  src/app/(home)/meeting/_components/AttendeeProfiles.tsx
  src/app/(home)/meeting/_components/Pagination.tsx
  src/app/(home)/meeting/_components/footer.test.tsx
  src/app/(home)/meeting/_components/pagination.test.tsx
  src/app/(home)/mypage/components/ProfileForm/FormControl.tsx
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.test.tsx
  src/app/(home)/mypage/components/ProfileForm/ProfileForm.tsx
  src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.test.tsx
  src/app/(home)/mypage/components/ProfileIcon/ProfileIcon.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/Button/LikeButton.tsx
  src/components/Filtering/__tests__/FilterDropdown.test.tsx
  src/components/Filtering/__tests__/FilterListCustom.test.tsx
  src/components/GNB/Header.tsx
  src/components/InputSection/HideToggleButton.tsx
  src/components/Login/Login.activeButton.test.tsx
  src/components/Login/Login.hideToggleButton.test.tsx
  src/components/Login/Login.onBlur.test.tsx
  src/components/Login/Login.onFocus.test.tsx
  src/components/Login/Login.onSubmit.test.tsx
  src/components/Login/Login.tsx
  src/components/PageNav/__tests__/PageNavbarCustom.test.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/components/Signup/Signup.onBlur.test.tsx
  src/components/Signup/Signup.onFocus.test.tsx
  src/components/Signup/Signup.tsx
  src/hooks/customs/__tests__/useFilters.test.ts
Labels: 배포 관련 라벨
